### ISSUE TITLE
Web browser process supervision

### ISSUE THREAD

**Issue by ethanjli** [pez-globo/pufferfish-software#65]
We will need some way to start the web browser at startup of the RPi; it will need to start only *after* the HTTP server (which will serve the frontend website to the web browser) has started; and it will also need to automatically restart the web browser if it crashes (and it will need to remove any temporary files after a crash). Importantly, the web browser should start with regular user privileges, not with superuser/root privileges.

It is also possible that we will need to restart the entire web browser if the frontend's browser tab crashes or freezes. In this case, we might need the backend server to be able to (directly or indirectly) kill any web browser processes on the operating system if the backend server detects that it has lost its WebSocket connection to the frontend for more than ~1 second. And of course the web browser will need to be automatically restarted after it is killed.

**Comment by Tanmay06** [comment]
I've a prototype ready in the PR #201 could we simulate the scenario to test it though?

**Comment by Tanmay06** [comment]
I was wondering whether it is a good idea to keep the browser process supervision as synchronous task in the `server.py` or we could launch it as an async task to I/O ops in `_trio.py`. Keeping it async will give us better control on the kill frontend process calls. Instead of keeping a track of last spawned  `killall` process, we can use `subp.wait()` and `trio.Event()` to control the triggering of `kill_frontend()` method. Further more, this will also reduce any hindrance caused by the current implementation to regular the `backend` tasks.

**Comment by ethanjli** [comment]
Hopefully https://github.com/pez-globo/pufferfish-vent-software/pull/201#pullrequestreview-507971191 addresses your questions above
